upstream api {
    server agripewebapi:8080;
}

server {
    listen 80;

    location /api/ {
        proxy_pass http://api;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
