// Minimal mock for react-native-reanimated in Jest
const Reanimated = {
  default: {
    call: jest.fn(),
    event: jest.fn(),
    Value: jest.fn(),
    createAnimatedComponent: (component: unknown) => component,
    View: 'View',
    Text: 'Text',
    Image: 'Image',
    ScrollView: 'ScrollView',
  },
  useSharedValue: (v: unknown) => ({ value: v }),
  useAnimatedStyle: (fn: () => unknown) => fn(),
  withTiming: (v: unknown) => v,
  withSpring: (v: unknown) => v,
  withDecay: (v: unknown) => v,
  withRepeat: (v: unknown) => v,
  withDelay: (_delay: unknown, v: unknown) => v,
  withSequence: (...args: unknown[]) => args[args.length - 1],
  runOnJS: (fn: (...args: unknown[]) => unknown) => fn,
  runOnUI: (fn: (...args: unknown[]) => unknown) => fn,
  useAnimatedGestureHandler: jest.fn(),
  useAnimatedScrollHandler: jest.fn(),
  useAnimatedRef: jest.fn(() => ({ current: null })),
  useAnimatedReaction: jest.fn(),
  useDerivedValue: (fn: () => unknown) => ({ value: fn() }),
  Easing: { linear: (v: number) => v, bezier: jest.fn(), inOut: jest.fn() },
  interpolate: jest.fn((value: number) => value),
  Extrapolation: { CLAMP: 'clamp', EXTEND: 'extend', IDENTITY: 'identity' },
  createAnimatedComponent: (component: unknown) => component,
  View: 'Animated.View',
  Text: 'Animated.Text',
  Image: 'Animated.Image',
  ScrollView: 'Animated.ScrollView',
  FlatList: 'Animated.FlatList',
};

module.exports = Reanimated;
